### ISSUE TITLE
Npm install not working.

### ISSUE THREAD

**Issue by Hardik21** [DAppDevConsulting/EasyTCR#2]
npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t ssh://git@github.com/DAppDevConsulting/tcr-api.git
npm ERR!
npm ERR! Host key verification failed.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128

**Comment by ryzhak** [comment]
https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/

**Comment by Hardik21** [comment]
I have installed python v2.7.14 & node v8.7.0 & also added ssh key in my account. But it display same error.

**Comment by Hardik21** [comment]
Thanks. Its work.
