### ISSUE TITLE
When i change contract address

### ISSUE THREAD

**Issue by Hardik21** [DAppDevConsulting/EasyTCR#3]
`uncaught at root at root 
 at flow 
 at takeLatest 
 at init 
 Error: Couldn't decode address from ABI: 0x`

Where to set contract ABI?

**Comment by hodkov** [comment]
Hi!
Contract abi defined here:  https://github.com/DAppDevConsulting/tcr-api

You can change contract address in cfg.json https://github.com/DAppDevConsulting/EasyTCR/blob/master/src/cfg.json

contract must be deployed into network `network` (4 for rinkeby)

**Comment by Hardik21** [comment]
`{
  "IPFS": {
    "gateway": "https://ipfs.infura.io",
    "apiServer": "https://ipfs.infura.io:5001"
  },
  "WEB3": {
    "http": "https://rinkeby.infura.io/Pltg02Lba51HKyNBEFop"
  },
  "network": "4",
  "TCRofTCRs": {
    "registry": "0xFfBb87e0bC197306415cA60b3D9013cf7d7585a2"
  }
}`


This is what i took change in cfg.json file.

I deployed contract in rinkeby network.

But still same error display.
