### ISSUE TITLE
Whitelisted/successful registry applicants aren't visible in the web UI

### ISSUE THREAD

**Issue by tylev** [DAppDevConsulting/EasyTCR#5]
I've been testing the repo with several TCRs based on mgoldin's implementation on the Rinkeby network and have deployed a parent registry ("0xf30b5fc08fa57b084ff5bbb41ab53737232fb332") and submitted a child registry ("0xf62391156eefc4696325d7a149da76f70517fcb6") to it. I've also made some applications to the child registry (e.g. listinghash "0x58d90e7a4d71aabc0dfe41805bab3379d324186b63a46df6d5e8da153548992c") using the web interface and I'm able to see those transaction and the corresponding event "_Application" on Etherscan: https://rinkeby.etherscan.io/address/0xf62391156eefc4696325d7a149da76f70517fcb6#events

However, despite the "updateStatus" transactions succeeding and the TCR contract updating to show isWhitelisted=true, the entries don't show up in the EasyTCR web UI. Any ideas why?

**Comment by hodkov** [comment]
May be "updateStatus" transaction is not sucessfull?

https://rinkeby.etherscan.io/address/0xf62391156eefc4696325d7a149da76f70517fcb6

**Comment by tylev** [comment]
It looks like the first "updateStatus" transaction was successful:
https://rinkeby.etherscan.io/tx/0x63ea42f06ef39d8d84d8233c73996f1606cdcfdb1e40af13093a569a47bb5f9f

And when I call `isWhitelisted` on the contract, my listinghash does show `true`.

<img width="944" alt="screenshot 2018-07-28 09 01 36" src="https://user-images.githubusercontent.com/5290890/43357336-7725fc18-9245-11e8-8727-1604cfed405f.png">

In the EasyTCR UI, however the `listings` array is empty and I'm not seeing any other JS errors in the console. 

http://tcr.dappdev.org/token_holder/0xf62391156eefc4696325d7a149da76f70517fcb6

**Comment by tylev** [comment]
closing as I was able to resolve this issue by updating the contract ABIs in the `ethereum-tcr-api` package
